"""deleted refresh token

Revision ID: c2e99c2ff1fb
Revises: bc5ef07c6be0
Create Date: 2025-12-09 09:58:40.932343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e99c2ff1fb'
down_revision = 'bc5ef07c6be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('refresh_token_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
